version: '3.1'

services:

  pymongo:
    image: pymongo:0.1
    restart: always
    volumes:
      - ../db-helper/db-helper.py:/app/db-helper.py
      - ../db-helper/data.json:/app/data.json
    command: tail -f /dev/null
    
  mongo:
    image: mongo:3.4.23-xenial
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: thisispassword
